# Generated by Django 5.2.1 on 2026-04-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('mname', models.CharField(max_length=300)),
                ('hero', models.CharField()),
                ('heroine', models.CharField()),
            ],
        ),
    ]
